{{- if .Values.customerSimulationService.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "customerSimulation.serviceAccountName" . }}
  labels:
    {{- include "customerSimulation.labels" . | nindent 4 }}
  {{- with .Values.customerSimulationService.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
