{{- if .Values.fepumpService.deploy -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fepump.serviceName" . }}
  labels:
    {{- include "fepump.labels" . | nindent 4 }}
spec:
  type: {{  .Values.fepumpService.serviceType | default "ClusterIP "}}
  ports:
  - name: http
    port: {{ include "fepump.servicePort" . }}
    targetPort: 80
  selector:
    {{- include "fepump.selectorLabels" . | nindent 4 }}
{{- end -}}
