{{- if .Values.fepumpService.deploy -}}
{{- if .Values.openshift -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "fepump.name" . }}-external
  labels:
    {{- include "fepump.labels" . | nindent 4 }}
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "fepump.serviceName" . }}
{{ end }}
{{- end -}}

