apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemis
metadata:
 name: ex-aao
spec:
  deploymentPlan:
    size: 3
    image: registry.redhat.io/amq7/amq-broker:7.6
    requireLogin: false
  adminUser: admin
  adminPassword: admin
  console:
    expose: true
  acceptors:
  - name: amqp
    protocols: amqp
    port: 5672
    sslEnabled: true
    sslSecret: ex-aao-amqp-secret
    verifyHost: false
    expose: true
  - name: mqtt
    protocols: mqtt
    port: 8883
    sslEnabled: true
    sslSecret: ex-aao-mqtt-secret
    verifyHost: false
    expose: true
               