{{- if .Values.decisionService.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "decision.serviceAccountName" . }}
  labels:
    {{- include "decision.labels" . | nindent 4 }}
  {{- with .Values.decisionService.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
