apiVersion: v1
kind: Service
metadata:
  name: {{ include "decision.serviceName" . }}
  labels:
    {{- include "decision.labels" . | nindent 4 }}
spec:
  type: {{  .Values.decisionService.serviceType | default "ClusterIP" }}
  ports:
  - name: http
    port: {{ include "decision.servicePort" . }}
    targetPort: 8080

  selector:
    {{- include "decision.selectorLabels" . | nindent 4 }}
