export STORE_HEIGHT=10
export STORE_WIDTH=6
export CUSTOMERS_AVERAGE_IN_STORE=6
export CUSTOMERS_LIST_FILE='customers.csv'
export MQTT_HOST='127.0.0.1'
export MQTT_CLIENT_ID=test

export LOG_LEVEL=INFO

export USE_REDIS_BACKEND=false
export REDIS_HOST=127.0.0.1
export REDIS_PORT=6379
export REDIS_DB=0
#REDIS_PASSWORD=

export CONSUME_FREQUENCY=1
export CONSUME_FROM=earliest
export CONSUME_BATCH_SIZE=32