{{- if .Values.cachedbLoader.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cachedbLoader.serviceAccountName" . }}
  labels:
    {{- include "cachedbLoader.labels" . | nindent 4 }}
  {{- with .Values.cachedbLoader.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
