apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "visualization.labels" . | nindent 4 }}
  name: {{ include "visualization.name" . }}
spec:
  replicas: {{ .Values.customerSimulationService.replicas }}
  selector:
    matchLabels:
    {{- include "visualization.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "visualization.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccount: {{ include "visualization.serviceAccountName" . }}
      containers:
      - name: gui
        image: {{ tpl .Values.visualization.image . }}
        env:
        {{- if and .Values.visualization.fastApi  }}
        {{- range .Values.visualization.fastApi.env }}
        - name: {{ .name }}
          value: {{ .value | quote}}
        {{- end }}
        {{- end }}
        - name: SCENARIO_PLAYER_SCENARIO_ENDPOINT
          value: "http://{{  include "customerSimulation.serviceName" . }}:{{include "customerSimulation.servicePort" . }}/scenario"
        {{- if .Values.globalInfra.mqtt.brokerServer }}
        - name: MQTT_HOST
          value: {{  .Values.globalInfra.mqtt.brokerServer | quote }}
        {{- end }}
        {{- if .Values.globalInfra.mqtt.brokerPort }}
        - name: MQTT_PORT
          value: {{  .Values.globalInfra.mqtt.brokerPort  | quote }}
        {{- end }}
        {{- if .Values.globalInfra.mqtt.enterTopic }}
        - name: ENTER_TOPIC
          value: {{  .Values.globalInfra.mqtt.enterTopic | quote }}
        {{- end }}
        {{- if .Values.globalInfra.mqtt.moveTopic }}
        - name: MOVE_TOPIC
          value: {{  .Values.globalInfra.mqtt.moveTopic | quote }}
        {{- end }}
        {{- if .Values.globalInfra.mqtt.exitTopic }}
        - name: EXIT_TOPIC
          value: {{  .Values.globalInfra.mqtt.exitTopic | quote }}
        {{- end }}
        {{- if .Values.globalInfra.mqtt.browseTopic }}
        - name: BROWSING_TOPIC
          value: {{  .Values.globalInfra.mqtt.browseTopic | quote }}
        {{- end }}
        {{- if .Values.globalInfra.mqtt.couponsTopic }}
        - name: COUPON_PREDICTION_TOPIC
          value: {{  .Values.globalInfra.mqtt.couponsTopic | quote }}
        {{- end }}
        {{- if .Values.globalInfra.mqtt.sslEnabled }}
        - name: MQTT_BROKER_CERT_FILE
          value: /certs/broker_ca.crt
        {{- end }} 
        {{- if .Values.globalInfra.mqtt.authenticationEnabled }}
        envFrom:
        - secretRef:
            name: mqtt-auth-creds
        {{- end }}
        {{- if .Values.globalInfra.mqtt.sslEnabled }}
        volumeMounts:
        - name: broker-cert
          readOnly: true
          mountPath: /certs
        {{- end }}
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
    {{- if .Values.globalInfra.mqtt.sslEnabled }}
      volumes:
      - name: broker-cert
        secret:
          secretName: mqtt-broker-ca
          defaultMode: 0400
      {{- end }}
