{{- if .Values.visualization.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "visualization.serviceAccountName" . }}
  labels:
    {{- include "visualization.labels" . | nindent 4 }}
  {{- with .Values.visualization.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
